// // Generated by https://quicktype.io
// //
// // To change quicktype's target language, run command:
// //
// //   "Set quicktype target language"

// class User {
//   int id;
//   String name;
//   String username;
//   String email;
//   Address address;
//   String phone;
//   String website;
//   Company company;

//   User({
//     this.id,
//     this.name,
//     this.username,
//     this.email,
//     this.address,
//     this.phone,
//     this.website,
//     this.company,
//   });
// }

// class Address {
//   String street;
//   String suite;
//   String city;
//   String zipcode;
//   Geo geo;

//   Address({
//     this.street,
//     this.suite,
//     this.city,
//     this.zipcode,
//     this.geo,
//   });
// }

// class Geo {
//   String lat;
//   String lng;

//   Geo({
//     this.lat,
//     this.lng,
//   });
// }

// class Company {
//   String name;
//   String catchPhrase;
//   String bs;

//   Company({
//     this.name,
//     this.catchPhrase,
//     this.bs,
//   });
// }
